services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test:
        - "CMD-SHELL"
        - "cub zk-ready localhost 2181"
    volumes:
      - zookeeper-logs:/var/lib/zookeeper/log
      - zookeeper-data:/var/lib/zookeeper/data
  kafka:
    depends_on:
      zookeeper:
        condition: service_healthy
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test:
        - "CMD-SHELL"
        - "cub kafka-ready -b kafka:9092 1 10"
      interval: 10s
      timeout: 10s
      retries: 30
    volumes:
      - kafka-data:/var/lib/kafka/data
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      kafka: http://0.0.0.0:8081
    healthcheck:
      test:
        - "CMD-SHELL"
        - "cub sr-ready schema-registry 8081 5"
  ksqldb:
    image: confluentinc/ksqldb-server:0.28.2
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: ksqldb
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_NAME: __default_ksql_processing_log
      KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
      KSQL_CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      KSQL_CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "__ksql-connect-configs"
      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "__ksql-connect-offsets"
      KSQL_CONNECT_STATUS_STORAGE_TOPIC: "__ksql-connect-statuses"
      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      KSQL_CONNECT_PLUGIN_PATH: "/home/appuser/plugins"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "curl -sf http://localhost:8088/healthcheck"
    command:
      - bash
      - -c
      - |
        echo "===> Launching KSQL"
        /usr/bin/docker/run
  kafka-ui:
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      ksqldb:
        condition: service_healthy
    image: provectuslabs/kafka-ui:master
    ports:
      - "8080:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_KSQLDBSERVER: http://ksqldb:8088
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: ksqldb
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://ksqldb:8083
    healthcheck:
      test:
        - "CMD-SHELL"
        - "cub kafka-ready -b kafka:9092 1 10"
      interval: 10s
      timeout: 10s
      retries: 30
volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
